// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    cache_keys_max: 10000,
    cache_keys_check_interval: 60 * 1000
  };

}).call(this);

//# sourceMappingURL=memoize.config.js.map
